// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5v4DrrnwEUVs6jXrYwwtNtC3kapm-vQY',
    appId: '1:467891607021:web:e300b108924bfbfd3703e4',
    messagingSenderId: '467891607021',
    projectId: 'trialtask1-31562',
    authDomain: 'trialtask1-31562.firebaseapp.com',
    storageBucket: 'trialtask1-31562.appspot.com',
    measurementId: 'G-XGS7HV41JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZedUkagM8X-LQNDHYI8AWtTKda7g1fJg',
    appId: '1:467891607021:android:6f32be951d7011293703e4',
    messagingSenderId: '467891607021',
    projectId: 'trialtask1-31562',
    storageBucket: 'trialtask1-31562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs3SbETcMF8TgSzVMZp5g29r1R2Ur192Y',
    appId: '1:467891607021:ios:dec75f57759374713703e4',
    messagingSenderId: '467891607021',
    projectId: 'trialtask1-31562',
    storageBucket: 'trialtask1-31562.appspot.com',
    iosBundleId: 'com.example.trialTask01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs3SbETcMF8TgSzVMZp5g29r1R2Ur192Y',
    appId: '1:467891607021:ios:dec75f57759374713703e4',
    messagingSenderId: '467891607021',
    projectId: 'trialtask1-31562',
    storageBucket: 'trialtask1-31562.appspot.com',
    iosBundleId: 'com.example.trialTask01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5v4DrrnwEUVs6jXrYwwtNtC3kapm-vQY',
    appId: '1:467891607021:web:cc8b004d7519f5eb3703e4',
    messagingSenderId: '467891607021',
    projectId: 'trialtask1-31562',
    authDomain: 'trialtask1-31562.firebaseapp.com',
    storageBucket: 'trialtask1-31562.appspot.com',
    measurementId: 'G-FPZPHWBTTH',
  );
}